### PR TITLE
partially merging the work done by 2 dev's on the same component.

### PR DESCRIPTION
**Pull request by elsahib**
I have added a couple of components and also added react-router. there are a few extra touches to make it look better to follow soon

### CODE REVIEW

**Review by wriggy — COMMENTED** [review]
The code runs but I am getting a new  error message about a missing 'key' prop at VolunteerOpportunity.- this is usually related to a list. I am trying to find out what causes the error and how to fix. (I don't get this error on the version in main).

**Comment by wriggy** [comment]
I have removed a couple of lines of App.js to fix the key error on the become a volunteer route. The rest looks good. (though I didn't get the search to work in the header.. not sure if it's fully implemented yet). NB we will need to be careful with 'filteredOpportunities' as the state is used separately in the become a volunteer route and App.js. An issue for a future refactor. 
I am happy for Osman to merge when he has reviewed my change. Good work!

**Comment by elsahib** [comment]
I have fixed the error you were getting about missing key prop, please have a look.

**Review by wriggy — APPROVED** [review]
Looks good.

**Pull request merged**
